export const COMMON_TARGETS = [
	{ MinAge: '18' },
	{ Age: '18 and older' },
	{ Region: 'the United States' },
	{ Retargeting: 'people who may be similar to their customers' },
	{ List: '' },
	{ Like: '' },
	{ Website: 'people who have visited their website or used one of their apps' },
	{ 'Activity on the Facebook Family': '' },
	{ Segment: 'US politics (very liberal)' },
	{ MinAge: '25' },
	{ MinAge: '35' },
	{ Gender: 'women' },
	{ Age: '25 and older' },
	{ Age: '35 and older' },
	{ MinAge: '30' },
	{ Age: '30 and older' },
	{ MinAge: '21' },
	{ Age: '21 and older' },
	{ State: 'California' },
	{ Region: 'California' },
	{ MinAge: '45' },
	{ Region: 'Florida' },
	{ Age: '45 and older' },
	{ Region: 'Texas' },
	{ MinAge: '40' },
	{ Age: '40 and older' },
	{ Segment: 'US politics (liberal)' },
	{ Gender: 'men' },
	{ MinAge: '50' },
	{ Interest: 'Democratic Party (United States)' },
	{ Age: '50 and older' },
	{ State: 'New York' },
	{ State: 'Texas' },
	{ MinAge: '55' },
	{ State: 'Florida' },
	{ Interest: 'Barack Obama' },
	{ Region: 'Michigan' },
	{ Region: 'Washington' },
	{ Age: '55 and older' },
	{ Region: 'Colorado' },
	{ Segment: 'US politics (moderate)' },
	{ Region: 'New York' },
	{ Interest: 'Bernie Sanders' },
	{ Region: 'Ohio' },
	{ Region: 'Massachusetts' },
	{ Region: 'Minnesota' },
	{ Retargeting: 'recently near their business' },
	{ State: 'Washington' },
	{ Segment: 'US politics (very conservative)' },
	{ Region: 'Arizona' },
	{ State: 'Minnesota' },
	{ State: 'Illinois' },
	{ Age: '13 and older' },
	{ MinAge: '24' },
	{ MinAge: '13' },
	{ State: 'Michigan' },
	{ City: 'New York' },
	{ Region: 'Wisconsin' },
	{ State: 'Pennsylvania' },
	{ Region: 'Missouri' },
	{ City: 'Washington' },
	{ Region: 'North Carolina' },
	{ Interest: 'Donald Trump' },
	{ Region: 'Pennsylvania' },
	{ Age: '24 and older' },
	{ MaxAge: '54' },
	{ MaxAge: '49' },
	{ Segment: 'Member of a family-based household.' },
	{ MinAge: '22' },
	{ State: 'Virginia' },
	{ Interest: 'Planned Parenthood' },
	{ Region: 'Georgia' },
	{ Region: 'Nevada' },
	{ Segment: 'US politics (conservative)' },
	{ Age: '22 and older' },
	{ State: 'District of Columbia' },
	{ Interest: 'Politics and social issues' },
	{ State: 'Maryland' },
	{ Region: 'Illinois' },
	{ MaxAge: '64' },
	{ Region: 'North Dakota' },
	{ State: 'North Carolina' },
	{ State: 'Missouri' },
	{ State: 'Ohio' },
	{ Region: 'Oregon' },
	{ Region: 'Montana' },
	{ State: 'Arizona' },
	{ Segment: 'Likely to engage with political content (liberal)' },
	{ Age: '65' },
	{ MinAge: '65' },
	{ MaxAge: '65' },
	{ Language: 'English (US)' },
	{ Interest: 'Politics' },
	{ Interest: 'Republican Party (United States)' },
	{ MaxAge: '55' },
	{ Segment: 'Multicultural affinity: African American (US).' },
	{ Region: 'Iowa' },
	{ MinAge: '20' },
	{ MaxAge: '34' },
	{ State: 'Oregon' },
];
