export const COMMON_TARGETS = [
	{ target: 'MinAge', segment: '18' },
	{ target: 'Age', segment: '18 and older' },
	{ target: 'Region', segment: 'the United States' },
	{ target: 'Retargeting', segment: 'people who may be similar to their customers' },
	{ target: 'List', segment: '' },
	{ target: 'Like', segment: '' },
	{ target: 'Website', segment: 'people who have visited their website or used one of their apps' },
	{ target: 'Activity on the Facebook Family', segment: '' },
	{ target: 'Segment', segment: 'US politics (very liberal)' },
	{ target: 'MinAge', segment: '25' },
	{ target: 'MinAge', segment: '35' },
	{ target: 'Gender', segment: 'women' },
	{ target: 'Age', segment: '25 and older' },
	{ target: 'Age', segment: '35 and older' },
	{ target: 'MinAge', segment: '30' },
	{ target: 'Age', segment: '30 and older' },
	{ target: 'MinAge', segment: '21' },
	{ target: 'Age', segment: '21 and older' },
	{ target: 'State', segment: 'California' },
	{ target: 'Region', segment: 'California' },
	{ target: 'MinAge', segment: '45' },
	{ target: 'Region', segment: 'Florida' },
	{ target: 'Age', segment: '45 and older' },
	{ target: 'Region', segment: 'Texas' },
	{ target: 'MinAge', segment: '40' },
	{ target: 'Age', segment: '40 and older' },
	{ target: 'Segment', segment: 'US politics (liberal)' },
	{ target: 'Gender', segment: 'men' },
	{ target: 'MinAge', segment: '50' },
	{ target: 'Interest', segment: 'Democratic Party (United States)' },
	{ target: 'Age', segment: '50 and older' },
	{ target: 'State', segment: 'New York' },
	{ target: 'State', segment: 'Texas' },
	{ target: 'MinAge', segment: '55' },
	{ target: 'State', segment: 'Florida' },
	{ target: 'Interest', segment: 'Barack Obama' },
	{ target: 'Region', segment: 'Michigan' },
	{ target: 'Region', segment: 'Washington' },
	{ target: 'Age', segment: '55 and older' },
	{ target: 'Region', segment: 'Colorado' },
	{ target: 'Segment', segment: 'US politics (moderate)' },
	{ target: 'Region', segment: 'New York' },
	{ target: 'Interest', segment: 'Bernie Sanders' },
	{ target: 'Region', segment: 'Ohio' },
	{ target: 'Region', segment: 'Massachusetts' },
	{ target: 'Region', segment: 'Minnesota' },
	{ target: 'Retargeting', segment: 'recently near their business' },
	{ target: 'State', segment: 'Washington' },
	{ target: 'Segment', segment: 'US politics (very conservative)' },
	{ target: 'Region', segment: 'Arizona' },
	{ target: 'State', segment: 'Minnesota' },
	{ target: 'State', segment: 'Illinois' },
	{ target: 'Age', segment: '13 and older' },
	{ target: 'MinAge', segment: '24' },
	{ target: 'MinAge', segment: '13' },
	{ target: 'State', segment: 'Michigan' },
	{ target: 'City', segment: 'New York' },
	{ target: 'Region', segment: 'Wisconsin' },
	{ target: 'State', segment: 'Pennsylvania' },
	{ target: 'Region', segment: 'Missouri' },
	{ target: 'City', segment: 'Washington' },
	{ target: 'Region', segment: 'North Carolina' },
	{ target: 'Interest', segment: 'Donald Trump' },
	{ target: 'Region', segment: 'Pennsylvania' },
	{ target: 'Age', segment: '24 and older' },
	{ target: 'MaxAge', segment: '54' },
	{ target: 'MaxAge', segment: '49' },
	{ target: 'Segment', segment: 'Member of a family-based household.' },
	{ target: 'MinAge', segment: '22' },
	{ target: 'State', segment: 'Virginia' },
	{ target: 'Interest', segment: 'Planned Parenthood' },
	{ target: 'Region', segment: 'Georgia' },
	{ target: 'Region', segment: 'Nevada' },
	{ target: 'Segment', segment: 'US politics (conservative)' },
	{ target: 'Age', segment: '22 and older' },
	{ target: 'State', segment: 'District of Columbia' },
	{ target: 'Interest', segment: 'Politics and social issues' },
	{ target: 'State', segment: 'Maryland' },
	{ target: 'Region', segment: 'Illinois' },
	{ target: 'MaxAge', segment: '64' },
	{ target: 'Region', segment: 'North Dakota' },
	{ target: 'State', segment: 'North Carolina' },
	{ target: 'State', segment: 'Missouri' },
	{ target: 'State', segment: 'Ohio' },
	{ target: 'Region', segment: 'Oregon' },
	{ target: 'Region', segment: 'Montana' },
	{ target: 'State', segment: 'Arizona' },
	{ target: 'Segment', segment: 'Likely to engage with political content (liberal)' },
	{ target: 'Age', segment: '65' },
	{ target: 'MinAge', segment: '65' },
	{ target: 'MaxAge', segment: '65' },
	{ target: 'Language', segment: 'English (US)' },
	{ target: 'Interest', segment: 'Politics' },
	{ target: 'Interest', segment: 'Republican Party (United States)' },
	{ target: 'MaxAge', segment: '55' },
	{ target: 'Segment', segment: 'Multicultural affinity: African American (US).' },
	{ target: 'Region', segment: 'Iowa' },
	{ target: 'MinAge', segment: '20' },
	{ target: 'MaxAge', segment: '34' },
	{ target: 'State', segment: 'Oregon' },
];

export const COMMON_TARGETS_GROUPED = {
	MinAge: [
		'13',
		'18',
		'20',
		'21',
		'22',
		'24',
		'25',
		'30',
		'35',
		'40',
		'45',
		'50',
		'55',
		'59',
		'65' ],
	Region: [
		'the United States',
		'California',
		'Florida',
		'Texas',
		'Michigan',
		'Washington',
		'Colorado',
		'New York',
		'Ohio',
		'Massachusetts',
		'Minnesota',
		'Arizona',
		'Wisconsin',
		'Missouri',
		'North Carolina',
		'Pennsylvania',
		'Georgia',
		'Nevada',
		'Illinois',
		'North Dakota',
		'Oregon',
		'Montana',
		'Iowa' ],
	Retargeting: [
		'people who may be similar to their customers',
		'recently near their business' ],
	List: [ '' ],
	Like: [ '' ],
	Website: [ 'people who have visited their website or used one of their apps' ],
	'Activity on the Facebook Family': [ '' ],
	Segment:[
		'US politics (very liberal)',
		'US politics (liberal)',
		'US politics (moderate)',
		'US politics (conservative)',
		'US politics (very conservative)',
		'Member of a family-based household.',
		'Likely to engage with political content (liberal)',
		'Likely to engage with political content (conservative)',
		'Multicultural affinity: African American (US).',
		'Multicultural affinity: Asian American (US).',
		'Multicultural affinity: Hispanic (US - All).',
		'Multicultural affinity: Hispanic (US - English dominant).',
		'Multicultural affinity: Hispanic (US - Bilingual).',
		'Multicultural affinity: Hispanic (US - Spanish dominant).'],
	Gender: [ 'women', 'men' ],
	Interest: [
		'Democratic Party (United States)',
		'Barack Obama',
		'Bernie Sanders',
		'Donald Trump',
		'Planned Parenthood',
		'Politics and social issues',
		'Politics',
		'Republican Party (United States)',
		'Sean Hannity', ],
	Language: [ 'English (US)' ],
};
